# CMake generated Testfile for 
# Source directory: /home/roko/desktop/projects/LFUCache/IdealCache
# Build directory: /home/roko/desktop/projects/LFUCache/IdealCache
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test1 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test1.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test1.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test1.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test1 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test10 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test10.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test10.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test10.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test10 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test11 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test11.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test11.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test11.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test11 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test12 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test12.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test12.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test12.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test12 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test13 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test13.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test13.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test13.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test13 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test2 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test2.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test2.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test2.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test2 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test3 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test3.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test3.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test3.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test3 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test4 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test4.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test4.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test4.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test4 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test5 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test5.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test5.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test5.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test5 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test6 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test6.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test6.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test6.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test6 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test7 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test7.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test7.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test7.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test7 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test8 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test8.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test8.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test8.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test8 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
add_test(test9 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/IdealCache/bin/IdealCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test9.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test9.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/IdealCache/tests/test9.ans" "-P" "/home/roko/desktop/projects/LFUCache/IdealCache/cmake/RunTest.cmake")
set_tests_properties(test9 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/IdealCache/CMakeLists.txt;0;")
