# CMake generated Testfile for 
# Source directory: /home/roko/desktop/projects/LFUCache/LFUCache
# Build directory: /home/roko/desktop/projects/LFUCache/LFUCache
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test1 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/LFUCache/bin/LFUCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test1.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test1.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test1.ans" "-P" "/home/roko/desktop/projects/LFUCache/LFUCache/cmake/RunTest.cmake")
set_tests_properties(test1 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;0;")
add_test(test2 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/LFUCache/bin/LFUCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test2.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test2.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test2.ans" "-P" "/home/roko/desktop/projects/LFUCache/LFUCache/cmake/RunTest.cmake")
set_tests_properties(test2 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;0;")
add_test(test3 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/LFUCache/bin/LFUCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test3.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test3.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test3.ans" "-P" "/home/roko/desktop/projects/LFUCache/LFUCache/cmake/RunTest.cmake")
set_tests_properties(test3 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;0;")
add_test(test4 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/LFUCache/bin/LFUCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test4.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test4.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test4.ans" "-P" "/home/roko/desktop/projects/LFUCache/LFUCache/cmake/RunTest.cmake")
set_tests_properties(test4 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;0;")
add_test(test5 "/usr/bin/cmake" "-DTEST_PROGRAM=/home/roko/desktop/projects/LFUCache/LFUCache/bin/LFUCache" "-DTEST_INPUT=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test5.dat" "-DTEST_OUTPUT=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test5.out" "-DTEST_EXPECTED=/home/roko/desktop/projects/LFUCache/LFUCache/tests/test5.ans" "-P" "/home/roko/desktop/projects/LFUCache/LFUCache/cmake/RunTest.cmake")
set_tests_properties(test5 PROPERTIES  _BACKTRACE_TRIPLES "/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;36;add_test;/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;54;add_lfu_test;/home/roko/desktop/projects/LFUCache/LFUCache/CMakeLists.txt;0;")
